import React from 'react';

import { useAppContext } from '../context/AppContext';

const LegalPage: React.FC = () => {
  const { setShowLegalPage } = useAppContext();
  const currentYear = new Date().getFullYear();

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-950 via-slate-900 to-slate-800 text-white py-8 px-4">
      <div className="max-w-3xl mx-auto bg-white text-gray-900 dark:bg-gray-800 dark:text-gray-100 rounded-lg shadow-lg p-6">
        <button onClick={() => setShowLegalPage(false)} className="text-blue-600 hover:underline mb-4 inline-block">
          &larr; Back
        </button>
        <h1 className="text-2xl font-bold border-b border-gray-300 pb-2 mb-4">Privacy Policy</h1>
        <p><strong>Effective Date:</strong> April 23, 2025</p>

        <h2 className="text-xl font-semibold mt-6 mb-2">1. Data Collection and Usage</h2>
        <p>We do not collect personal data such as your name, email address, or precise location directly.</p>
        <p>However, we use <strong>Google Analytics</strong> to understand user interactions with the App. This service may collect anonymized data including:</p>
        <ul className="list-disc list-inside">
          <li>Device type and browser</li>
          <li>Visited pages and duration</li>
          <li>Approximate geographic location</li>
          <li>Traffic source</li>
        </ul>
        <p>This information helps us improve the performance and usability of the App.</p>

        <h2 className="text-xl font-semibold mt-6 mb-2">2. Cookies</h2>
        <p>The App may use cookies through Google Analytics. Cookies are small text files stored on your device to enhance your experience and help us analyze usage.</p>
        <p>By using the App, you consent to the use of cookies via Google Analytics. You can disable cookies via your browser settings at any time.This web application contains affiliate links to external websites (e.g., Trip.com, Airalo, Tiqets.com), which may use cookies in accordance with their own privacy policies.</p>

        <h2 className="text-xl font-semibold mt-6 mb-2">3. Affiliate Links and Support</h2>
        <p>While the App is free to use and not sold as a commercial product, it may contain affiliate links to help cover operational costs. If you choose to book services through affiliate partners (e.g., Travelpayouts), we may receive a small commission &mdash; at no additional cost to you. These funds help us maintain and improve the App.</p>
        <p>You may also choose to support the App voluntarily through platforms such as <strong>&ldquo;Buy Me a Coffee or other services&rdquo;</strong>. Donations are entirely optional and do not grant access to additional features.</p>
        <p>We are not responsible for the content, services, or policies of any third-party websites linked through the App. Please review their terms and privacy policies separately.</p>

        <h2 className="text-xl font-semibold mt-6 mb-2">4. Route Generation Disclaimer</h2>
        <p>All routes generated by the App are for informational purposes only. We do not guarantee their accuracy, safety, or completeness.</p>
        <p>Use of the App and generated routes is entirely at your own risk. We are not liable for any damages, delays, or incidents resulting from the use of these routes.</p>

        <h2 className="text-xl font-semibold mt-6 mb-2">5. Data Retention</h2>
        <p>We do not store any personal data directly. Aggregated, anonymized analytics data may be retained by Google Analytics according to their policies.</p>

        <h2 className="text-xl font-semibold mt-6 mb-2">6. Your Rights</h2>
        <p>If you are an EU/EEA resident, you have rights under GDPR, including access to and deletion of your data. For more details, see the <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline">Google Privacy Policy</a>.</p>

        <h1 className="text-2xl font-bold mt-8 border-b border-gray-300 pb-2 mb-4">Terms of Use</h1>
        <ul className="list-disc list-inside">
          <li>You agree to use the App for lawful purposes only.</li>
          <li>The App is provided &ldquo;as-is&rdquo;, with no warranties.</li>
          <li>Route data may not reflect real-time conditions such as road closures or safety hazards.</li>
          <li>The developers are not liable for any loss, damage, or inconvenience from using the App.</li>
        </ul>

        <h1 className="text-2xl font-bold mt-8 border-b border-gray-300 pb-2 mb-4">Copyright Notice</h1>
        <p>All content and design of this App are &copy; [Suave.Studio.PL], {currentYear}.</p>
        <p>Map data &copy; OpenStreetMap contributors. Routing data provided by third-party APIs subject to their respective licenses.</p>

        <h1 className="text-2xl font-bold mt-8 border-b border-gray-300 pb-2 mb-4">Contact</h1>
        <p>If you have any questions, feedback, or concerns, feel free to reach out to us at:</p>
        <p className="mt-2 font-semibold text-blue-400">
          <a href="mailto:citybreak.world@gmail.com" className="hover:underline">citybreak.world@gmail.com</a>
        </p>
      </div>
    </div>
  );
};

export default LegalPage;
